[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
[[redirects]]
from = "/android-chrome-512x512.png"
to = "/favicon.svg"
status = 302
[[redirects]]
from = "/favicon.png"
to = "/favicon.svg"
status = 302
[[redirects]]
from = "/favicon.ico"
to = "/favicon.svg"
status = 302
[[redirects]]
from = "/posts/index.xml"
to = "/rss.xml"
status = 302
[[redirects]]
from = "/rss"
to = "/rss.xml"
status = 302
[[redirects]]
from = "/rss/"
to = "/rss.xml"
status = 302
[[redirects]]
from = "/feed"
to = "/rss.xml"
status = 302
[[redirects]]
from = "/feed/"
to = "/rss.xml"
status = 302
[[redirects]]
from = "/collection/"
to = "/following.html"
status = 301
[[redirects]]
from = "/collections/"
to = "/following.html"
status = 301
[[redirects]]
from = "/copies/"
to = "/following.html"
status = 301
[[redirects]]
from = "/me/"
to = "/about.html"
status = 301
[[redirects]]
from = "/notes/"
to = "/diary.html"
status = 301
[[redirects]]
from = "/page/"
to = "/diary.html"
status = 301
[[redirects]]
from = "/posts/"
to = "/diary.html"
status = 301