[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
[[redirects]]
from = "/android-chrome-512x512.png"
to = "/favicon.png"
status = 302